nelmio_solarium:
    endpoints:
        default:
            host: "%env(SOLR_HOST)%"
            core: "%env(SOLR_CORE)%"
            port: "%env(SOLR_PORT)%"
            # scheme: http
            # path: /solr
            timeout: 30
    clients:
        default:
            endpoints: [default]
