---
# Name of your project, will also be the vagrant box name
project_name: "swissinfo-indexing"

# Main hostname through which the vagrant box will be accessible
hostname: "swissinfo-indexing.test"
# Alternative hostnames through which you want to access the vagrant box
hostnames: []

# Ports you want forwared to your host. See https://www.vagrantup.com/docs/networking/forwarded_ports.html
# for details.
forwarded_ports: {}

# Backingstore used by LXC. Defaults to dir. Uncomment and change this
# value to suit your needs.
# Note: only used with vagrant-lxc provider.
# backingstore: dir

# Virtual machine memory size use in MB. Defaults to 4096. Uncomment and change
# this value to suit your needs.
# Note: only used with VirtualBox provider.
# memory: 1024

# Virtual machine CPU's count use. Defaults to 2. Uncomment and change this
# value to suit your needs.
# Note: only used with VirtualBox provider.
# cpus: 1

# Root directory of your project for the webserver and other purposes
root_directory: "/vagrant/public"

# Synced folder type to use. Only "nfs" and "virtualbox" are supported by
# drifter. Defaults to "nfs". Uncomment the following line to use the
# Virtualbox shared folder implementation.
# synced_folder_type: "virtualbox"

# For a PHP project, you might want to set the following
# Default reporting level of PHP errors
php_error_reporting: "E_ALL & ~E_NOTICE"

# if you want to dissable ssh StrictHostKeyChecking (needs the ssh role)
# this has security issues, you better add your ssh host keys in the ssh role
# ssh_no_stricthostkeychecking: true

# If you want to use ubuntu instead of debian (or any other box),
# uncomment this. You can also replace "base" with "php7", if you need
# php7 (with fpm and nginx) anyway.
# box_name: "drifter/trusty64-base"
# box_url: "https://vagrantbox-public.liip.ch/drifter-trusty64-base.json"
php_version: 7.2