solrsearch:
    type: solr:6.6
    disk: 1024
    configuration:
        cores:
            mainindex:
                conf_dir: !archive "solrconf"
        endpoints:
            solr:
                core: mainindex
