solrsearch:
    type: solr:6.6
    disk: 512
    configuration:
        cores:
            mainindex:
                conf_dir: !archive "solrconf"
        endpoints:
            solr:
                core: mainindex

rabbitmq:
    type: rabbitmq:3.7
    disk: 512